const Map<String, String> enLanguagePackage = {
  "Mywallet": "My wallet",
  "Setting": "Setting",
  "Signout": "Sign out",
  "Darkmode": "Dark mode",
  "Entertheemailaccountthatyouwanttorecovery":
      "Enter the email account that you want to recovery",
  "SENDCODE": "SEND CODE",
  "Resetpassword": "Reset password",
  "Newpassword": "New password",
  "Confirmpassword": "Confirm password",
  "CONFIRM": "CONFIRM",
  "A4charactercodehasbeensenttotheemail":
      "A 4-character code has been sent to the email",
  "VERIFY": "VERIFY",
  "Didntreceiveanycode": "Didn't receive any code?",
  "Signin": "Sign in",
  "Password": "Password",
  "SIGNIN": "SIGN IN",
  "Forgotpassword": "Forgot password?",
  "Signup": "Sign up",
  "SIGNUP": "SIGNUP",
  "ManageyourfinanceseffectivelywithMoneyKeeper":
      "Manage your finances effectively with MoneyKeeper",
  "Cutunnecessaryexpenses": "Cut unnecessary expenses",
  "Increasesavingssteadilyeverymonth": "Increase savings steadily every month",
  "Manageitallinoneplace": "Manage it all in one place",
  "SIGNUPFORFREE": "SIGN UP FOR FREE",
  "Home": "Home",
  "Transaction": "Transaction",
  "Report": "Report",
  "Account": "Account",
  "Lastweek": "Last week",
  "Thisweek": "This week",
  "Lastmonth": "Last month",
  "Thismonth": "This month",
  "Nextmonth": "Next month",
  "Totalbalance": "Total balance",
  "Seemore": "See more",
  "All": "All",
  "Detail": "Detail",
  "Week": "Week",
  "Month": "Month",
  "Totalexpenseofthisweek": "Total expense of this week",
  "Totalexpenseofthismonth": "Total expense of this month",
  "Mostexpense": "Most expense",
  "Recently": "Recently",
  "Addwallet": "Add wallet",
  "Editwallet": "Edit wallet",
  "Walletname": "Wallet name",
  "Balance": "Balance",
  "Notincludeintotalbalance": "Not include in total balance",
  "Createanewwalletanddonotincludeitintototalbalance":
      "Create a new wallet and do not include it into total balance",
  "ADDNEW": "ADD NEW",
  "DELETETHISWALLETFOREVER": "DELETE THIS WALLET FOREVER",
  "UPDATE": "UPDATE",
  "Including": "Including",
  "Week1": 'Week 1',
  "Week2": 'Week 2',
  "Week3": 'Week 3',
  "Week4": 'Week 4',
  "Expensedetail": "Expense detail",
  "Totalexpense": "Total expense",
  "Incomedetail": "Income detail",
  "Totalincome": "Total income",
  "IncomeandExpense": "Income and Expense",
  "Totalleft": "Total left",
  "Income": "Income",
  "Expense": "Expense",
  "Newtransaction": "New transaction",
  "Save": "Save",
  "Selectcategory": "Select category",
  "Note": "Note",
  "Edittransaction": "Edit transaction",
  "Viewreportofthisperiod": "View report of this period",
  "Pleaseenteralltheinformation": "Please enter all the information",
  "Incorectcode": "Incorrect code",
  "Incorectpassword": "Incorrect password",
  "Vietnamese": "Vietnamese",
  "Type": "Type",
  "ManageCategory": "Category",
  "Categoryname": "Category name",
  "Planning": "Planning",
  "Budget": "Budget",
  "Afinancial":
      "A financial plan that helps you balance your income and expenses",
  "Event": "Event",
  "Createaneventto":
      "Create an event to track a real event, for example a weekend trip",
  "Running": "Running",
  "Finished": "Finished",
  "Addevent": "Add event",
  "Editevent": "Edit event",
  "Eventname": "Event name",
  "Enddate": "End date",
  "Selectwallet": "Select wallet",
  "Spent": "Spent",
  "Markasfinished": "Mark as finished",
  "Markasunfinished": "Mark as unfinished",
  "Listoftransaction":"List of transaction",
};
