const Map<String, String> viLanguagePackage = {
  "Mywallet": "Ví của tôi",
  "Setting": "Cài đặt",
  "Signout": "Đăng xuất",
  "Darkmode": "Chế độ ban đêm",
  "Entertheemailaccountthatyouwanttorecovery":
      "Nhập địa chỉ email mà bạn muốn khôi phục mật khẩu",
  "SENDCODE": "GỬI MÃ",
  "Resetpassword": "Khôi phục mật khẩu",
  "Newpassword": "Mật khẩu mới",
  "Confirmpassword": "Xác nhận mật khẩu",
  "CONFIRM": "XÁC NHẬN",
  "A6charactercodehasbeensenttotheemail":
      "Một mã gồm 6 ký tự đã được gửi đến email",
  "VERIFY": "XÁC MINH",
  "Didntreceiveanycode": "Không nhận được mã?",
  "Signin": "Đăng nhập",
  "Password": "Mật khẩu",
  "SIGNIN": "ĐĂNG NHẬP",
  "Forgotpassword": "Quên mật khẩu?",
  "Signup": "Đăng ký",
  "SIGNUP": "ĐĂNG KÝ",
  "ManageyourfinanceseffectivelywithMoneyKeeper":
      "Quản lý tài chính hiệu quả với MoneyKeeper",
  "Cutunnecessaryexpenses": "Cắt giảm những chi phí không cần thiết",
  "Increasesavingssteadilyeverymonth": "Gia tăng tiết kiệm đều đặn hàng tháng",
  "Manageitallinoneplace": "Quản lý tất cả ở một nơi",
  "SIGNUPFORFREE": "ĐĂNG KÝ MIỄN PHÍ",
  "Home": "Trang chủ",
  "Transaction": "Thu chi",
  "Report": "Thống kê",
  "Account": "Tài khoản",
  "Lastweek": "Tuần trước",
  "Thisweek": "Tuần này",
  "Lastmonth": "Tháng trước",
  "Thismonth": "Tháng này",
  "Nextmonth": "Tháng sau",
  "Totalbalance": "Tổng số dư",
  "Seemore": "Xem thêm",
  "All": "Toàn bộ",
  "Detail": "Chi tiết",
  "Week": "Tuần",
  "Month": "Tháng",
  "Totalexpenseofthisweek": "Tổng chi tuần này",
  "Totalexpenseofthismonth": "Tổng chi tháng này",
  "Mostexpense": "Chi nhiều nhất",
  "Recently": "Gần đây",
  "Addwallet": "Thêm ví mới",
  "Editwallet": "Chỉnh sửa ví",
  "Walletname": "Tên ví",
  "Balance": "Số dư",
  "Notincludeintotalbalance": "Không bao gồm vào ví tổng",
  "Createanewwalletanddonotincludeitintototalbalance":
      "Tạo ví này và không bao gồm số dư của nó vào ví tổng",
  "ADDNEW": "THÊM MỚI",
  "DELETETHISWALLETFOREVER": "XOÁ VĨNH VIỄN VÍ NÀY",
  "UPDATE": "CẬP NHẬT",
  "Including": "Bao gồm",
  "Week1": 'Tuần 1',
  "Week2": 'Tuần 2',
  "Week3": 'Tuần 3',
  "Week4": 'Tuần 4',
  "Expensedetail": "Chi tiết khoản chi",
  "Totalexpense": "Tổng chi",
  "Incomedetail": "Chi tiết khoản thu",
  "Totalincome": "Tổng thu",
  "IncomeandExpense": "Thu và Chi",
  "Totalleft": "Còn lại",
  "Income": "Khoản thu",
  "Expense": "Khoản chi",
  "Newtransaction": "Giao dịch mới",
  "Save": "Lưu",
  "Selectcategory": "Chọn danh mục",
  "Note": "Ghi chú",
  "Edittransaction": "Sửa khoản chi",
  "Viewreportofthisperiod": "Xem thống kê kỳ này",
  "Pleaseenteralltheinformation": "Vui lòng điền đủ thông tin",
  "Incorectcode": "Mã không hợp lệ",
  "Incorectpassword": "Mật khẩu không khớp",
  "Vietnamese": "Tiếng Việt",
  "Type":"Khoản",
};
